### PR TITLE
Enforce requirement that name and plural name be unique.

### PR DESCRIPTION
**Pull request by jheizer**
Ensure controller routes are unique if you accidently make the names the same.

### CODE REVIEW

**Comment by jheizer** [comment]
Completely missed there were custom exception classes for everything.

**Comment by pdevito3** [comment]
Hey, just seeing these. Not sure I want to move forward with this one as there are theoretically some names that are the same as plural (e.g. moose, music, news, etc.). Let me know if I'm missing something though and I'll look at it again.

**Comment by jheizer** [comment]
You end up with duplicate routes

> System.InvalidOperationException: 'The following errors occurred with attribute routing information:
> 
> Error 1:
> Attribute routes with the same name 'GetThings' must have the same template:
> Action: 'WebApi.Controllers.v1.ThingsController.GetThings (WebApi)' - Template: 'api/Things'
> Action: 'WebApi.Controllers.v1.ThingsController.GetThings (WebApi)' - Template: 'api/Things/{thingsId}''

**Comment by pdevito3** [comment]
Ah, interesting. Good catch! Might be better to make an endpoint name generator function in the utils that will do what it's doing now by default, but if the singular and plural are the same, it can generate something different like `GetIndividualMoose`. That way, people can still be grammatically correct and get a working endpoint. ￼

**Comment by pdevito3** [comment]
resolved this with a dynamic naming convention in the 0.6 branch for next release so consumers can use grammatically correct names. 

Regardless, thanks again for the contribution! If there's anything else you'd like to help with let me know! Would love to have additional support.

**Pull request closed without merging**
