### PR TITLE
Use author name and email from global gitconfig for initial commit

### PR DESCRIPTION
**Pull request by sshquack**
Currently the initial commit uses a default author and email. This causes commits to get rejected when a repo in GitHub has strict commit author / email checks enabled. Fix this by pulling the global gitconfig author for the initial commit. See [libgit2 tests](https://github.com/libgit2/libgit2sharp/blob/df3b22a754ef56da8d7e3c330ce2d783c2b7982e/LibGit2Sharp.Tests/CommitFixture.cs#L563)

### CODE REVIEW

**Comment by pdevito3** [comment]
Fair enough! Could you just add a bullet in the changelog under `Unreleased`?

**Comment by pdevito3** [comment]
Remembered why I did this originally. Using myself for a scaffolded project was blowing up my git history on GitHub saying that I had huge commits on those days, so I didn't want it tied to me. 

I'll probably add a bool toggle to the domain project template to use yourself or the craftsman alias with you being the default.

**Comment by sshquack** [comment]
> Fair enough! Could you just add a bullet in the changelog under `Unreleased`?

Done! Feel free to edit the wording. Sorry for the whitespace trim again. It would be nice to add a build step to use the official [dotnet-format](https://github.com/dotnet/format) tool for consistent styling for contributors.

> I'll probably add a bool toggle to the domain project template to use yourself or the craftsman alias with you being the default.

Ah gotcha. That sounds good to me. Alternatively there could be a global ~/.craftsman_config file (similar to ~/.gitconfig) for internal config flags. Another thing that could go in the global config is to prevent double prompts. For example: any time scaffold is used, it prompts to star the repo. If a user said "y", then that could be store in the global ~/.craftsman_config. Just some ideas for later.

**Comment by pdevito3** [comment]
Yeah agreed on the formatting. Just haven't been motivated enough to care about it yet. Want to do a rewrite soon anyway to clean up a bunch of stuff so even less concerned atm lol

I've had various ideas floating around about some kind of a config file as well for a while. Could theoretically add a lot more flexibility to project setup and scaffolding, but would be a big shift and add a good bit of complexity. Regardless, do want to explore it one day.

**Comment by sshquack** [comment]
I hear ya! Totally just ideas for when you are revamping the code. Looking forward to it. Happy weekend 🍻

**Comment by pdevito3** [comment]
Always appreciate the input! Happy weekend 🍻

**Review by pdevito3 — APPROVED** [review]

**Pull request merged**
